require("init")

it("toString", function()
  assert.same(toString(1), "1")
end)

it("isArray", function()
  assert.True(isArray({}))
  assert.True(isArray({ 1 }))
  assert.False(isArray({ a = 1 }))
  assert.False(isArray("a"))
end)

describe("List", function()
  it("construction", function()
    local list = List(1, 2, 3)
    assert.same({ 1, 2, 3 }, list.items)
    assert.True(isA(list, List))
  end)
  describe("from", function()
    it("primitive", function()
      local list = List:from(1)
      assert.same({ 1 }, list.items)
    end)
    it("array", function()
      local list = List:from({ 1, 2, 3 })
      assert.same({ 1, 2, 3 }, list.items)
    end)
    it("List", function()
      local list = List:from(List(1, 2, 3))
      assert.same({ 1, 2, 3 }, list.items)
    end)
  end)
  it("pairs", function()
    local list = List(1, 2, 3)
    local i = 0
    for _, v in pairs(list) do
      i = i + 1
      assert.same(i, v)
    end
  end)
  it("length", function()
    local list = List(1, 2, 3)
    assert.same(list:length(), 3)
  end)
  it("at", function()
    local list = List(1, 2, 3)
    assert.same(1, list:at(0))
    assert.same(2, list:at(1))
    assert.same(3, list:at(-1))
    assert.same(2, list:at(-2))
  end)
end)
